### ISSUE TITLE
!IMPORTANT! TLS failing on connection

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [meebey/smuxi#275]
When I try to connect to my network using smuxi with client and local server (I've installed the all in one package), I get the following error:
```
17:24:43 -!- Connecting to irc.ptirc.org port 6697...
17:24:44 -!- Connection failed! Reason: Could not connect to: irc.ptirc.org:6697 The authentication or decryption has failed.
17:25:00 -!- Connecting to irc.ptirc.org port 6697...
17:25:01 -!- Connection failed! Reason: Could not connect to: irc.ptirc.org:6697 The authentication or decryption has failed.
17:25:01 -!- Not connected
```
I'm currently using UnrealIRCd v4.0.17 with the TLS v1.0 protocol to incoming connections disabled.

When I go to `Help -> About`, this is what appears:
```
Smuxi
Vendor: Debian 2:1.0+stable.bzr535~ubuntu17.10.1
Frontend: GNOME 1.0.0.0
Engine: 1.0.0.0
```

Any idea would be highly appreciated.
Thanks in advance

**Comment by knocte** [comment]
What mono version are you using?

**Comment by meebey** [comment]
Mono has a known history of TLS compatibility issues. So many issues that I dedicated a FAQ page on it and how to make it work, see https://smuxi.im/faq/troubleshooting/linux-tls/

[As of Mono version 4.8 the TLS engine was switched to BoringSSL][Mono-4.8] and TLS works very well since then.
Make sure you use Mono 4.8 or newer and please re-open this issue if you still experience issues with encrypted IRC connections.
 [Mono-4.8]: https://www.mono-project.com/docs/about-mono/releases/4.8.0/
